#ifndef SERIAL_ORDER_H
#define SERIAL_ORDER_H

enum Order {
  HELLO = 10,
  CONNECTED = 11,
  RECEIVED = 12,
  ERROR = 13,

  GET_IDENTIFIER = 20,
  SET_IDENTIFIER = 21,

  GET_SERVO_ANGLE = 30,
  SET_SERVO_ANGLE = 31,

  GET_MIN_PWM = 40,
  SET_MIN_PWM = 41,
  GET_MAX_PWM = 42,
  SET_MAX_PWM = 43,

  GET_ZERO_RAW_POSITION = 50,
  SET_ZERO_RAW_POSITION = 51,

  GET_GRAVITY_FEED_FORWARD = 60,
  SET_GRAVITY_FEED_FORWARD = 61,
};

typedef enum Order Order;

#endif
